[package]
name = "helixir-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.2"
helix-db = "0.1.3"
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["macros", "rt"] }
anyhow = "1.0.98"
serde_json = "1.0.130"